# Generated by Django 4.2.16 on 2024-10-25 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=100)),
                ('workreason', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('important', models.BooleanField(default=False)),
                ('payment_pdf', models.FileField(blank=True, null=True, upload_to='payments/pdfs/')),
                ('payment_image', models.ImageField(blank=True, null=True, upload_to='payments/images/')),
                ('payment_xml', models.FileField(blank=True, null=True, upload_to='payments/xmls/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
